**1.1 Основные идеи NumPy**

In [2]:
import numpy as np

In [2]:
np.sqrt(17)

4.123105625617661

In [3]:
np.log(4)

1.3862943611198906

In [4]:
np.mean([4,3,46,53,42,3])

25.166666666666668

In [5]:
np.median([4,3,46,53,42,3])

23.0

**1.4 Ndarray: базовая концепция**

In [7]:
np.array([2,3,4])

array([2, 3, 4])

In [9]:
np.array([[2,3,4],
        [3,4,5]])

array([[2, 3, 4],
       [3, 4, 5]])

In [10]:
np.array([[[2,3,4],
           [2,4,5]],
           
           [[4,5,6],
        [3,4,5]]])

array([[[2, 3, 4],
        [2, 4, 5]],

       [[4, 5, 6],
        [3, 4, 5]]])

In [12]:
np.array([[2,3,4], [0,1]])

C:\Windows\Temp\ipykernel_12924\1157647257.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[2,3,4], [0,1]])


array([list([2, 3, 4]), list([0, 1])], dtype=object)

In [14]:
np.array([["Kate", "Ann"],[24,34]])

array([['Kate', 'Ann'],
       ['24', '34']], dtype='<U11')

**1.5 Ndarray: операции**

In [16]:
turnout = np.array([4,3,5])
turnout

array([4, 3, 5])

In [17]:
turnout * 100

array([400, 300, 500])

In [18]:
turnout + np.array([4,3,5])

array([ 8,  6, 10])

In [19]:
turnout**2

array([16,  9, 25])

**1.6 Базовые операции над массивами**

In [44]:
m = np.array([[3,3],
             [4,5],
             [7,6]])

In [45]:
m.ndim #определение какой массив

2

In [46]:
m.shape

(3, 2)

In [47]:
m.size

6

In [48]:
m[1][1]

5

In [49]:
m[2:]

array([[7, 6]])

In [50]:
m[1, 1]

5

In [51]:
m[::-1]

array([[7, 6],
       [4, 5],
       [3, 3]])

**1.7 Вычисления с массивами**

In [53]:
marks = np.array([1,2,3,4,5])

In [54]:
marks.min()

1

In [56]:
marks.max()

5

In [58]:
marks.mean()

3.0

In [60]:
marks.argmax()

4

In [61]:
marks.argmin()

0

In [62]:
grades = np.array([[3,5,5,4,3],
                   [3,3,4,3,3],
                   [5,5,5,4,3]])

In [63]:
print(grades)

[[3 5 5 4 3]
 [3 3 4 3 3]
 [5 5 5 4 3]]


In [64]:
grades.mean(axis = 1) #по каждому массиву, т.е. студентку как тут

array([4. , 3.2, 4.4])

In [66]:
grades.mean(axis = 0) #по столбцу

array([3.66666667, 4.33333333, 4.66666667, 3.66666667, 3.        ])

**1.8 Создание массивов**

In [67]:
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [68]:
np.arange(2,9,3)

array([2, 5, 8])

In [70]:
np.arange(2,9,0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5])

In [5]:
z = np.zeros((5))
z

array([0., 0., 0., 0., 0.])

In [7]:
o = np.ones((5,5))
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
e = np.eye(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**1.9 Условия и булевы массивы**

In [12]:
a = 6 
b = 7
b > a

True

In [13]:
b >= a

True

In [14]:
a == b

False

In [16]:
ages = np.array([
    [15,23,32,45,52],
    [68,34,55,78,20],
    [25,67,33,45,14]
])

In [17]:
ages >= 16

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [19]:
M = ages>=16
M

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [22]:
work = (ages>18)&(ages<28)

In [23]:
work.sum()

3

In [24]:
(ages<18) | (ages>28)

array([[ True, False,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False,  True,  True,  True,  True]])

In [25]:
ages[ages >= 16]

array([23, 32, 45, 52, 68, 34, 55, 78, 20, 25, 67, 33, 45])

In [27]:
ages[(ages >= 16) & (ages < 60)]

array([23, 32, 45, 52, 34, 55, 20, 25, 33, 45])